---
name: Deploy to Dokku (DEV)

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

permissions:
  contents: read


jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DOKKU_HOST: ${{ secrets.DOKKU_HOST }}
    steps:
      - name: Cloning repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DOKKU_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "${{ secrets.DOKKU_HOST }}" >> ~/.ssh/known_hosts

      - name: Deploy to Dokku
        env:
          DOKKU_HOST: ${{ secrets.DOKKU_HOST }}
          DOKKU_APP_NAME: ${{ vars.DOKKU_APP_NAME }}
        uses: dokku/github-action@master
        with:
          branch: ${{ github.ref_name }}
          git_remote_url: ssh://dokku@${{ secrets.DOKKU_HOST }}/${{ vars.DOKKU_APP_NAME }}
          ssh_private_key: ${{ secrets.DOKKU_SSH_PRIVATE_KEY }}